CXX			= c++
CXXFLAGS	= -Wall -Wextra -Werror -std=c++98

TARGET		= instantiation

SRCS		= main.cpp AMateria.cpp MateriaSource.cpp IMateriaSource.cpp \
				ICharacter.cpp Character.cpp Cure.cpp Ice.cpp 
OBJDIR		= obj
OBJS		= $(SRCS:%.cpp=$(OBJDIR)/%.o)

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $(OBJS)

$(OBJDIR)/%.o: %.cpp | $(OBJDIR)
	$(CXX) $(CXXFLAGS) -c $< -o $@

$(OBJDIR):
	mkdir -p $(OBJDIR)

clean:
	rm -rf $(OBJDIR)

fclean: clean
	rm -rf $(TARGET) 

re: fclean all

.PHONY: all clean fclean re